services:
  db:
    image: postgres:15-alpine
    container_name: my_project_db_local
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${DATABASE_NAME:-app_db}
    volumes:
      - ./postgres/local-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
